CREATE TABLE NHACC
(
   MANCC VARCHAR(20) NOT NULL PRIMARY KEY,
   TENNCC VARCHAR(20),
   DIACHI VARCHAR(20),
   DTHOAI VARCHAR(20),
   EMAIL VARCHAR(20)
);

CREATE TABLE SANPHAM
(
  MASP VARCHAR(20) NOT NULL PRIMARY KEY,
  TENSP VARCHAR(20),
  SOLUONG INT,
  DONGIA NUMBER,
  MANCC VARCHAR(20)
);

CREATE TABLE PHIEUNHAP 
(
  MAPN VARCHAR(20) NOT NULL PRIMARY KEY,
  NGAYLAP VARCHAR(20),
  GHICHU VARCHAR(20),
  TONGTIEN NUMBER
);

CREATE TABLE CT_NHAP
(
  MAPN VARCHAR(20),
  MASP VARCHAR(20),
  SL INT,
  CONSTRAINT PK_CT PRIMARY KEY (MAPN, MASP)
);



ALTER TABLE SANPHAM ADD CONSTRAINT FK1 FOREIGN KEY(MANCC) REFERENCES NHACC(MANCC);
ALTER TABLE CT_NHAP ADD CONSTRAINT FK2 FOREIGN KEY(MAPN) REFERENCES PHIEUNHAP(MAPN);
ALTER TABLE CT_NHAP ADD CONSTRAINT FK3 FOREIGN KEY(MASP) REFERENCES PHIEUNHAP(MASP);

CREATE SEQUENCE SQ_NCC INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SQ_SP INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE SQ_PN INCREMENT BY 1 START WITH 1;


CREATE OR REPLACE TRIGGER NHACC_AUTO
BEFORE INSERT ON NHACC
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT
    SQ_NCC.NEXTVAL INTO :NEW.MANCC
    FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER SP_AUTO
BEFORE INSERT ON SANPHAM
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT
    SQ_SP.NEXTVAL INTO :NEW.MASP
    FROM DUAL;
END;
/
CREATE OR REPLACE TRIGGER PN_AUTO
BEFORE INSERT ON PHIEUNHAP
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT
    SQ_PN.NEXTVAL INTO :NEW.MAPN
    FROM DUAL;
END;
/

CREATE TABLE DIENTHOAI
(
  IMEI VARCHAR(20) NOT NULL PRIMARY KEY,
  TENDT VARCHAR(20),
  LOAIDT VARCHAR(20),
  HOTENKH VARCHAR(20),
  SDTKH VARCHAR(20)
);

CREATE TABLE SUACHUA 
(
  MAPSC VARCHAR(20) NOT NULL PRIMARY KEY,
  NGAYLAP VARCHAR(20),
  NOIDUNG VARCHAR(20),
  IMEI VARCHAR(20), 
  TONGTIEN NUMBER
);

CREATE TABLE CONGVIEC 
( 
   MACV VARCHAR(20) NOT NULL PRIMARY KEY,
   TENCV VARCHAR(20),
   DONGIA NUMBER
);

CREATE TABLE CT_SC
(
  MAPSC VARCHAR(20),
  MACV VARCHAR(20),
  CONSTRAINT PK_CT1 PRIMARY KEY(MAPSC, MACV)
);

CREATE SEQUENCE SQ_SC INCREMENT BY 1 START WITH 1;

ALTER TABLE SUACHUA ADD CONSTRAINT FK4 FOREIGN KEY(IMEI) REFERENCES DIENTHOAI(IMEI);
ALTER TABLE CT_SC ADD CONSTRAINT FK5 FOREIGN KEY(MAPSC) REFERENCES SUACHUA(MAPSC);
ALTER TABLE CT_SC ADD CONSTRAINT FK6 FOREIGN KEY(MACV) REFERENCES CONGVIEC(MACV);

CREATE OR REPLACE TRIGGER PSC_AUTO
BEFORE INSERT ON SUACHUA
REFERENCING NEW AS NEW
FOR EACH ROW
BEGIN
SELECT
    SQ_SC.NEXTVAL INTO :NEW.MAPSC
    FROM DUAL;
END;

ALTER TABLE SUACHUA
MODIFY NOIDUNG NVARCHAR2(250);

INSERT INTO CONGVIEC(MACV, TENCV, DONGIA) VALUES ('1', 'CV A', 60000);
INSERT INTO CONGVIEC(MACV, TENCV, DONGIA) VALUES ('2', 'CV B', 160000);
INSERT INTO CONGVIEC(MACV, TENCV, DONGIA) VALUES ('3', 'CV C', 80000);
INSERT INTO CONGVIEC(MACV, TENCV, DONGIA) VALUES ('4', 'CV D', 500000);
INSERT INTO CONGVIEC(MACV, TENCV, DONGIA) VALUES ('5', 'CV E', 70000);
   
COMMIT;
    